eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: refresh,health, info
