server:
  port: 8081

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
#    tls:
#      enabled: false
#
#  instance:
#    prefer-ip-address: true
#
#logging:
#  level:
#    com.example.orderservice: DEBUG
#logging:
#  level:
#    org.springframework.cloud.config: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: refresh,health, info
