server:
  port: 8081

spring:
  application:
    name: product-service
custom:
  message: "Welcome to product Service! from config server"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
#    tls:
#      enabled: false
#
#  instance:
#    prefer-ip-address: true
#
#logging:
#  level:
#    com.example.orderservice: DEBUG
#logging:
#  level:
#    org.springframework.cloud.config: DEBUG
